/**********************************************************************/
/*
    CPX.H - constants for CPX.DLG
    CpPal (C) Copyright 2001 R L Walsh  All Rights Reserved
*/
/**********************************************************************/

// dialog IDs

#define IDD_MAIN    101
#define IDD_ERRBOX  109

#define IDI_ICON    101

#define IDP_SET     151
#define IDP_GET     152
#define IDP_ILL     153

#define IDC_LIST    201

#define IDC_CPPM    211
#define IDC_CPPROC  212
#define IDC_CP1     213
#define IDC_CP2     214
#define IDC_CP1TXT  215
#define IDC_CP2TXT  216

#define IDC_INFO    221
#define IDC_SET     222
#define IDC_GET     223

/**********************************************************************/

